# Generated by Django 5.1.7 on 2025-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20000.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
