# Generated by Django 5.1.7 on 2025-05-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carmodel_base_price_color_price_engine_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
