# Generated by Django 5.1.7 on 2025-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20000.0, max_digits=10, null=True),
        ),
    ]
