# Generated by Django 5.1.7 on 2025-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_colorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='offered_config',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='saved_config',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
