# Generated by Django 5.1.7 on 2025-05-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_configuration_offered_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='saved_config',
        ),
    ]
