# Generated by Django 5.1.7 on 2025-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_configuration_saved_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='offered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
