# Generated by Django 5.1.7 on 2025-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_configuration_offered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
