# Generated by Django 5.1.5 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_colorimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="saved_config",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
