# Generated by Django 5.1.7 on 2025-05-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
